### ISSUE TITLE
GHA release fails

### ISSUE THREAD

**Issue by strogonoff** [geolexica/isotc211-desktop#1]
The build passes fine, but an error seems to happen during release stage. It looks like a required token is missing in repository settings?

```
Error: Cannot cleanup: 
Error #1 --------------------------------------------------------------------------------
HttpError: 404 Not Found
"method: post url: https://api.github.com/repos/geolexica/isotc211-desktop/releases\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
```

The probably relevant part of GHA workflow is here: https://github.com/geolexica/isotc211-desktop/blob/master/.github/workflows/build-electron.yml#L39

**Comment by ronaldtse** [comment]
I haven't changed anything, but the latest build works? https://github.com/geolexica/isotc211-desktop/actions/runs/40353567

**Comment by strogonoff** [comment]
Same error on release stage I believe, the message is very explicitly about some token

**Comment by strogonoff** [comment]
I very vaguely recall we encountered this on GHA before on another Electron app, but not sure what was the resolution

**Comment by ronaldtse** [comment]
This is now fixed, see https://github.com/geolexica/isotc211-desktop/releases .
